branch-defaults:
  dbarch2:
    environment: ragbase-env
  main:
    environment: ragbase-env
    group_suffix: null
environment-defaults:
  ragbase-env:
    branch: null
    repository: null
global:
  application_name: ragbase
  branch: null
  default_ec2_keyname: rb
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
