name: Deploy Backend
on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Set environment variables based on branch
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "EB_ENVIRONMENT=ragbase-env" >> $GITHUB_ENV
          else
            echo "EB_ENVIRONMENT=rb-dev" >> $GITHUB_ENV
          fi
          echo "IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          
      - name: Build and push Docker image
        working-directory: ./backend
        env:
          ECR_REGISTRY: 509399637296.dkr.ecr.us-east-1.amazonaws.com
        run: |
          docker build -t $ECR_REGISTRY/ragbase:${{ env.IMAGE_TAG }} .
          docker push $ECR_REGISTRY/ragbase:${{ env.IMAGE_TAG }}
          
      - name: Install EB CLI
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli
          
      - name: Deploy to Elastic Beanstalk
        working-directory: ./backend
        run: |
          # Update Dockerrun.aws.json with new image tag
          sed -i 's|"Image": ".*"|"Image": "${{ env.ECR_REGISTRY }}/ragbase:${{ env.IMAGE_TAG }}"|' Dockerrun.aws.json
          eb deploy ${{ env.EB_ENVIRONMENT }} --timeout 20